name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Generate Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: puliczek/github-stats-actions@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          user: jeanlaris
          template: classic
          base: header, activity, community, repositories, metadata

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update generated stats [Skip GitHub Action]"
